import type { Metadata } from "next"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "@/components/ui/toaster"
import Chat from "@/components/chat/Chat"
import { ThemeProvider } from 'next-themes'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (

      <ClerkProvider>
        <html lang="en">
          <body className="antialiased">
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
            {children}
            <Chat />
            <Toaster />
                </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>

  )
}
